version: '3.8'

services:
  wazuh:  # 👈 THIS IS THE MANAGER SERVICE (YOU FIX THIS FIRST)
    image: wazuh/wazuh:4.12.0  # ✅ CORRECT TAG (with colon!)
    ports:
      - "192.168.50.1:55000:55000"  # Your existing port mapping (unchanged)
    # ... rest of your manager config (unchanged)
    volumes:
      - ./wazuh-data:/opt/wazuh/data
    command: ["-d", "--config", "/opt/wazuh/conf/wazuh-manager.conf"]
  wazuh-agent:
    image: wazuh/wazuh:4.12.0
    container_name: wazuh-agent
    volumes:
      - ./wazuh-agent-data:/opt/wazuh/agent
    command: ["-d", "--config", "/opt/wazuh/conf/wazuh-agent.conf"]
    # NO DEPENDS_ON (Wazuh agent runs independently)

  # Suricata (Network IDS) - Real-time traffic analysis
  suricata:
    image: suricata/suricata:5.0.0
    container_name: suricata
    ports:
      - "8080:8080"  # Suricata UI
      - "6206:6206"  # Suricata API
    volumes:
      - ./suricata-data:/opt/suricata/data
    command: ["-c", "/opt/suricata/etc/suricata.yaml"]

  # Zeek (Network Analysis) - Deep packet inspection
  zeek:
    image: zeek/zeek:4.0.0
    container_name: zeek
    ports:
      - "8081:8080"  # Zeek web UI (port 8080)
    volumes:
      - ./zeek-data:/opt/zeek/data
    command: ["-c", "/opt/zeek/etc/zeek.conf"]

  # OSSEC (Host-based IDS) - Endpoint monitoring
  ossec:
    image: ossec/ossec:3.0.0
    container_name: ossec
    ports:
      - "1514:1514"  # OSSEC agent port (for Wazuh integration)
    volumes:
      - ./ossec-data:/opt/ossec
    command: ["-d", "--config", "/opt/ossec/etc/ossec.conf"]

  # Nmap (Network scanning) - Recon tool
  nmap:
    image: nmap/nmap:7.9
    container_name: nmap
    command: ["nmap", "-sV", "-sC", "127.0.0.1"]  # Basic scan (no UI)
    volumes:
      - ./nmap-data:/opt/nmap

networks:
  soc-lab-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.50.0/24  # CHANGED FROM 192.168.100.0/24
          gateway: 192.168.50.1    # CHANGED FROM 192.168.100.1

