# docker-compose.yml (updated for SOC lab stability)
version: '3.8'

services:
  wazuh-manager:
    container_name: wazuh-manager
    ports:
      - "55000:55000"
    networks:
      - soc-lab-net
    healthcheck:
      test: ["CMD", "wazuh-manager", "--status"]
      interval: 30s
      timeout: 5s
      retries: 3

  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.12.0
    container_name: wazuh-dashboard
    ports:
      - "55001:55001"  # Your existing dashboard port (no changes)
    networks:
      - soc-lab-net
    depends_on:
      - wazuh-manager

  wazuh-indexer:
    image: wazuh/wazuh-indexer:4.12.0
    container_name: wazuh-indexer
    networks:
      - soc-lab-net
    depends_on:
      - wazuh-manager

  wazuh-agent:
    image: wazuh/wazuh-agent:4.12.0
    container_name: wazuh-agent
    networks:
      - soc-lab-net
    depends_on:
      - wazuh-manager
    command: ["wazuh-agent", "--server", "127.0.0.1:55000"]  # NO NETWORK EXPOSURE

  suricata:
    image: jasonish/suricata:4.0.0  # Specific version (no "latest")
    container_name: suricata
    networks:
      - soc-lab-net
    command: ["suricata", "-c", "/etc/suricata/suricata.yaml"]  # Minimal config

  zeek:
    image: zeek/zeek:1.5.0  # Specific version (no "latest")
    container_name: zeek
    networks:
      - soc-lab-net
    command: ["./bin/zeek", "-C", "/etc/zeek/zeek.conf"]  # Minimal config

  ossec:
    image: atomicorp/ossex-docker:1.0  # Fixed version (no "latest")
    container_name: ossec
    networks:
      - soc-lab-net
    command: ["ossec", "agent", "--server", "127.0.0.1:55000"]  # NO NETWORK EXPOSURE

    nmap:
    image: instrumentisto/nmap
    container_name: nmap
    networks:
      - soc-lab-net
    command: ["nmap", "-sV", "127.0.0.1"]

networks:
  soc-lab-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.50.0/24
          gateway: 192.168.50.1
