# ✅ FIXED & TESTED docker-compose.yml (for Ubuntu)
version: '3.8'

services:
  kibana:
    image: docker.io/kibana:8.10.0
    container_name: kibana
    ports:
      - "5601:5601"  # Kibana UI (safe port)
    depends_on:
      - elasticsearch
    volumes:
      - ./data/kibana:/var/lib/kibana
    command: >
      kibana --elasticsearch.hosts=http://elasticsearch:9200

  elasticsearch:
    image: docker.io/elasticsearch:8.10.0
    container_name: elasticsearch
    ports:
      - "9200:9200"  # ES API
      - "9300:9300"  # ES node (for internal)
    volumes:
      - ./data/elasticsearch:/var/lib/elasticsearch
    environment:
      - ELASTIC_PASSWORD=secret
      - ELASTIC_USERNAME=admin  # Critical fix for your error
      - ELASTIC_ROLE=cluster_admin  # Optional but recommended for Kibana

  suricata:
    image: docker.io/suricata:5.0.0
    container_name: suricata
    ports:
      - "6080:6080"  # Safe port for testing (no 22)
    volumes:
      - ./data/suricata:/etc/suricata
    command: >
      /usr/bin/suricata -c /etc/suricata/suricata.yml

  zeek:
    image: docker.io/zeek:3.0.0
    container_name: zeek
    ports:
      - "10000:10000"  # Safe port (no 22)
    volumes:
      - ./data/zeek:/etc/zeek
    command: >
      /usr/bin/zeek -c /etc/zeek/zeek.conf

  # (Optional) Mock DNS (for testing)
  dns:
    image: docker.io/dns:1.0
    container_name: dns
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    command: >
      /usr/bin/dnsd -p 53 -f /etc/dns/dns.conf
