version: '3.8'

services:
  wazuh:  # 👈 Wazuh manager (now on correct network)
    image: wazuh/wazuh:4.12.0
    ports:
      - "192.168.50.1:55000:55000"  # Your existing port mapping (unchanged)
    volumes:
      - ./wazuh-data:/opt/wazuh/data
    command: ["-d", "--config", "/opt/wazuh/conf/wazuh-manager.conf"]
    networks:
      - soc-lab-net  # 👈 CRITICAL ADDITION (all services now share this network)

  wazuh-agent:
    image: wazuh/wazuh:4.12.0
    container_name: wazuh-agent
    volumes:
      - ./wazuh-agent-data:/opt/wazuh/agent
    command: ["-d", "--config", "/opt/wazuh/conf/wazuh-agent.conf"]
    networks:
      - soc-lab-net  # 👈 CRITICAL ADDITION (now on same network)

  suricata:
    image: suricata/suricata:latest  # ✅ Fixed tag (as per your previous fix)
    ports:
      - "6206:6206"  # Suricata's default port (for lab testing)
    networks:
      - soc-lab-net  # 👈 Already had this (good)
    volumes:
      - ./suricata-data:/opt/suricata/data
    command: ["-c", "/opt/suricata/etc/suricata.yaml"]

  zeek:
    image: zeek/zeek:4.0.0
    container_name: zeek
    ports:
      - "8081:8080"  # Zeek web UI (port 8080)
    volumes:
      - ./zeek-data:/opt/zeek/data
    networks:
      - soc-lab-net  # 👈 Now on correct network
    command: ["-c", "/opt/zeek/etc/zeek.conf"]

  ossec:
    image: ossec/ossec:3.0.0
    container_name: ossec
    ports:
      - "1514:1514"  # OSSEC agent port (for Wazuh integration)
    volumes:
      - ./ossec-data:/opt/ossec
    networks:
      - soc-lab-net  # 👈 Now on correct network
    command: ["-d", "--config", "/opt/ossec/etc/ossec.conf"]

  nmap:
    image: nmap/nmap:7.9
    container_name: nmap
    networks:
      - soc-lab-net  # 👈 CRITICAL ADDITION (now on correct network)
    volumes:
      - ./nmap-data:/opt/nmap
    command: ["nmap", "-sV", "-sC", "127.0.0.1"]  # Basic scan (no UI)

networks:
  soc-lab-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.50.0/24  # Your target network (unchanged)
          gateway: 192.168.50.1    # Your gateway (unchanged)
