version: '3.8'

services:
  wazuh-manager:  # 👈 Wazuh manager (correct port for SOC)
    image: docker pull wazuh/wazuh-manager:4.12.0
    ports:
      - "192.168.50.1:55000:55000"  # Your existing port (critical for SOC)
    volumes:
      - ./wazuh-manager-data:/opt/wazuh/data
    networks:
      - soc-lab-net
    command: ["-d", "--config", "/opt/wazuh/conf/wazuh-manager.conf"]

  wazuh-dashboard:  # 👈 Wazuh dashboard (new service)
    image: dock pull wazuh/wazuh-dashboard:4.12.0
    ports:
      - "192.168.50.1:55001:55001"  # Dedicated port for dashboard (no conflict)
    depends_on:
      - wazuh-manager
    networks:
      - soc-lab-net
    command: ["-d", "--config", "/opt/wazuh/conf/dashboard.conf"]

  wazuh-indexer:  # 👈 Wazuh indexer (new service)
    image: docker pull wazuh/wazuh-indexer:4.12.0
    depends_on:
      - wazuh-manager
    volumes:
      - ./wazuh-indexer-data:/opt/wazuh/indexer
    networks:
      - soc-lab-net
    command: ["-d", "--config", "/opt/wazuh/conf/indexer.conf"]

  wazuh-agent:  # 👈 Wazuh agent (updated for SOC)
    image: docker pull wazuh/wazuh-agent:4.12.0
    container_name: wazuh-agent
    volumes:
      - ./wazuh-agent-data:/opt/wazuh/agent
    networks:
      - soc-lab-net
    command: ["-d", "--config", "/opt/wazuh/conf/agent.conf"]

  suricata:  # 👈 Updated to "jasonish/suricata:latest"
    image: docker pull jasonish/suricata:latest
    ports:
      - "6206:6206"  # Suricata default (for lab testing)
    networks:
      - soc-lab-net
    volumes:
      - ./suricata-data:/opt/suricata/data
    command: ["-c", "/opt/suricata/etc/suricata.yaml"]

  zeek:  # 👈 Updated to "zeek/zeek:latest"
    image: docker pull zeek/zeek:latest
    container_name: zeek
    ports:
      - "8081:8080"  # Zeek web UI (port 8080)
    volumes:
      - ./zeek-data:/opt/zeek/data
    networks:
      - soc-lab-net
    command: ["-c", "/opt/zeek/etc/zeek.conf"]

  ossec:  # 👈 Updated to "atomicorp/ossex-docker:latest"
    image: docker pull atomicorp/ossec-docker:latest
    container_name: ossec
    volumes:
      - ./ossec-data:/opt/ossec
    networks:
      - soc-lab-net
    command: ["-d", "--config", "/opt/ossec/etc/ossec.conf"]

  nmap:  # 👈 Updated to "instrumentisto/nmap"
    image: docker pull instrumentisto/nmap
    container_name: nmap
    networks:
      - soc-lab-net
    volumes:
      - ./nmap-data:/opt/nmap
    command: ["nmap", "-sV", "-sC", "127.0.0.1"]  # Local scan (no network exposure)

networks:
  soc-lab-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.50.0/24
          gateway: 192.168.50.1
